### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by cmd8** [animatedai/animatedai.github.io#1]
Great job on the animations!

Have you considered creating animations to visualize modern architectures such as Transformers or Attention mechanisms? It would be even better if you could write a guide on how others could make similar animations themselves and establish a central hub for people to upload their creations. This idea has the potential to take off and would greatly benefit those seeking a better understanding and visualization of the math behind these architectures.

Keep up the good work!

**Comment by animatedai** [comment]
Thank you! I appreciate the positive feedback.

Good news: I'm currently working on visualizations for Transformers and the self-attention mechanisms.

Bad news: the animations are currently made in Blender making heavy use of custom Geometry Nodes modifiers, so it wouldn't be easy for another person to use my work to produce similar animations unless they had quite a bit of prior knowledge of those topics. I'm always working to make it easier though, so perhaps one day...
