### ISSUE TITLE
[Video / Animation Request] Conv1D / Conv3D

### ISSUE THREAD

**Issue by tddschn** [animatedai/animatedai.github.io#2]
Hello,

I'm learning convnets and your animation videos on YouTube really helped me visualize and grok how Conv2D works intuitively.

Would you consider making animations for Conv1D / Conv3D layers?

Thanks,
Teddy

**Comment by animatedai** [comment]
Hi, thanks for the positive feedback! I do have Conv1D/3D animations planned. They're currently pretty far down in the queue, but I'll bump them up in priority a bit in response to your request :)
